### ISSUE TITLE
CompuMate PAL rom detected as NTSC

### ISSUE THREAD

**Issue by sa666666** [DirtyHairy/stella#34]
I guess we can always force this to be PAL in the properties (once the new core honours using ROM properties), but I think it may be a bug in the new auto-detect code.  In particular, the ROM has a scanline count of 324, which definitely means it should be PAL.

**Comment by DirtyHairy** [comment]
Weird, this detects as PAL for me. My ROM has the MD5 e7f005ddb6902c648de098511f6ae2e5 .

**Comment by sa666666** [comment]
Yes, that's the one.  When you turn on info with Alt+L, I see 324 scanlines and "NTSC*".  The '*' in this case means it autodetected as NTSC.  Also, the windows is sized at NTSC dimensions.  I know it is NTSC, since if you change NTSC aspect ratio it is applied, while changing the PAL aspect ratio does nothing.

The interesting thing is that when entering/exiting the debugger, the window changes height (to PAL dimensions), but it is still being identified as NTSC.

**Comment by DirtyHairy** [comment]
This is what I get:
![bildschirmfoto_2016-12-14_14-51-38](https://cloud.githubusercontent.com/assets/2444224/21184492/00961e2a-c20d-11e6-9877-eda8a0df4312.png)
Something must be different between our setups. I'll do a fresh build and check valgrind when I get home to be sure that nothing funky is happening on my side.

**Comment by thrust26** [comment]
Hm, for me the ROM doesn't work at all with pre1 (black screen). ALT+L info shows 0 @ 50.00fps => PAL | CM (16K)

With pre2 it works but shows what Stephen describes.

**Comment by sa666666** [comment]
There was a fix for Compumate ROMs in https://github.com/DirtyHairy/stella/commit/760d889478942b96920ca6f1632eff13ef7ed2fe, which happened after pre1 was released.  This new problem is with auto-detection of NTSC vs PAL.  It's showing 324 scanlines, so the autodetection should automatically make this PAL, regardless of what else is going on.

**Comment by DirtyHairy** [comment]
Fixed in 6500813 --- @sa666666 , could yo doublecheck that my fix doesn't have any unwelcome side effects as I am not familiar with this part of the code :smirk:?

Interestingly, I could reproduce the issue only after doing a `make clean` and rebuilding from scratch. What happened was basically

 * FrameManager starts out in NTSC mode
 * Without the proper controllers attached, CompuMate would not send `VSYNC`
 * The first frame would never finish, and thus the FrameManger would never leave NTSC mode
 * After starting the emulation proper, FrameManager would quickly detect PAL and switch, causing the jump in window dimensions, but as this change is not properly communicated, the Alt-l overlay would still read `NTSC*`
